### ISSUE TITLE
User interface mock-ups, sketches and wire-framing

### ISSUE THREAD

**Issue by Marian-Pinzariu** [cristinel-casu/WADe#1]
* Responsibility: collecting, tracing, review and integration of all artifacts
* Teammates will provide partial artifacts and feedback on others work

**Comment by cristinel-casu** [comment]
Added balsamiq moqups.

**Comment by cristinel-casu** [comment]
Added balsamiq moqups *.png exports.
Added website map.
Updated wiki page.
